//
//  bgSubtractor.hpp
//  UserViewer
//
//  Created by Zelun Luo on 1/13/16.
//  Copyright © 2016 Zelun Luo. All rights reserved.
//

#ifndef bgSubtractor_hpp
#define bgSubtractor_hpp

#include <stdio.h>
#include "helper.hpp"

using namespace cv;
using namespace std;

class BgSubtractor {
public:
    BgSubtractor(int w, int h);
    ~BgSubtractor();
    
    void processImages(Mat &img);
    void getBg(Mat &bg);
    void getMask(Mat &img, Mat &mask);
    
private:
    Mat fgMaskMOG2; // fg mask fg mask generated by MOG2 method
    Ptr<BackgroundSubtractor> pMOG2; // MOG2 Background subtractor
    int width;
    int height;
};

#endif /* bgSubtractor_hpp */
